import '../model/product_model.dart';

List<AllDresses> allProducts = [...Girls, ...mens, ...womens, ...boys];

List<AllDresses> Girls = [
  AllDresses(
    image: 'assets/kids/kid1.png',
    name: 'Below Knee Party Dress',
    price: 340.00,
    offer: 700,
    categories: 'kids',
  ),
  AllDresses(
    image: 'assets/kids/kid2.png',
    name: 'Girls Midi/Knee Length Casual Dress',
    price: 500.00,
    offer: 800,
    categories: 'kids',
  ),
  AllDresses(
    image: 'assets/kids/kid3.png',
    name: 'Girls Below Knee Casual Dress ',
    price: 280.00,
    offer: 400,
    categories: 'kids',
  ),
  AllDresses(
    image: 'assets/kids/girls.png',
    name: 'Girls Maxi/Full Length Festive ',
    price: 450.00,
    offer: 670,
    categories: 'kids',
  ),
  AllDresses(
    image: 'assets/kids/grl6.png',
    name: 'Girls Midi/Knee Length',
    price: 999.00,
    offer: 1200,
    categories: 'kids',
  ),
  AllDresses(
    image: 'assets/kids/grl7.png',
    name: 'Girls Midi/Knee Length',
    price: 460.00,
    offer: 600,
    categories: 'kids',
  ),
  AllDresses(
    image: 'assets/kids/grl8.png',
    name: 'Girls Midi/Knee Length',
    price: 1500.00,
    offer: 2000,
    categories: 'kids',
  ),
  AllDresses(
    image: 'assets/kids/grl10.png',
    name: 'Girls Midi/Knee Length',
    price: 1300.00,
    offer: 1700,
    categories: 'kids',
  ),
  AllDresses(
    image: 'assets/kids/kid2.png',
    name: 'Girls Midi/Knee Length',
    price: 1400.00,
    offer: 1800,
    categories: 'kids',
  ),
  AllDresses(
    image: 'assets/kids/kids4.png',
    name: 'Girls Midi/Knee Length',
    price: 290.00,
    offer: 450,
    categories: 'kids',
  ),
];

List<AllDresses> mens = [
  AllDresses(
    image: 'assets/mens/men1.png',
    name: ' Men Slim Mid Rise Blue Jeans',
    price: 1200.0,
    offer: 2000,
    categories: 'mens',
  ),
  AllDresses(
    image: 'assets/mens/men2.png',
    name: 'Men 2',
    price: 1999.0,
    offer: 2300,
    categories: 'mens',
  ),
  AllDresses(
    image: 'assets/mens/men3.png',
    name: 'Men Slim Mid Rise White Jeans',
    price: 500.0,
    offer: 700,
    categories: 'mens',
  ),
  AllDresses(
    image: 'assets/mens/men4.png',
    name: 'Men Regular Fit Solid Built-up Collar Casual Shirt',
    price: 700.0,
    offer: 999,
    categories: 'mens',
  ),
  AllDresses(
    image: 'assets/mens/men5.png',
    name: "Men Slim Fit Solid Spread Collar Casual Shirt",
    price: 650.0,
    offer: 800,
    categories: 'mens',
  ),
  AllDresses(
    image: 'assets/mens/men6.png',
    name: "Men Slim Fit Solid Spread Collar Casual Shirt",
    price: 999.0,
    offer: 800,
    categories: 'mens',
  ),
  AllDresses(
    image: 'assets/mens/men7.png',
    name: "Men Solid Polo Neck White T-Shirt",
    price: 199.0,
    offer: 400,
    categories: 'mens',
  ),
  AllDresses(
    image: 'assets/mens/men8.png',
    name: "Men Solid Polo Neck Dark Blue T-Shirt",
    price: 2999.0,
    offer: 3200,
    categories: 'mens',
  ),
  AllDresses(
    image: 'assets/mens/men9.png',
    name: "Men Solid Polo Neck Yellow T-Shirt",
    price: 790.0,
    offer: 900,
    categories: 'mens',
  ),
  AllDresses(
    image: 'assets/mens/men10.png',
    name: "Men Printed Polo Neck Red T-Shirt",
    price: 890.0,
    offer: 1200,
    categories: 'mens',
  ),
];

List<AllDresses> womens = [
  AllDresses(
    image: 'assets/womens/women1.png',
    name: 'Women Tiered Black Dress',
    price: 1200.0,
    offer: 1500,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/womens/women2.png',
    name: 'Women Fit and Flare Pink, Black Dress',
    price: 580.9,
    offer: 900,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/womens/women3.png',
    name: 'Women Fit and Flare Multicolor Dress',
    price: 499.0,
    offer: 600,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/womens/women4.png',
    name: 'Women Fit and Flare Dark Green, Yellow, Light Blue Dress',
    price: 340.0,
    offer: 600,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/womens/women5.png',
    name: 'Women Wrap Pink Dress',
    price: 500.0,
    offer: 799,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/womens/women6.png',
    name: 'Women Gown Black Dress',
    price: 890.0,
    offer: 1100,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/womens/women7.png',
    name: 'Women Fit and Flare White, Blue Dress',
    price: 230.0,
    offer: 400,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/womens/women8.png',
    name: 'Women Fit and Flare Black Dress',
    price: 450.0,
    offer: 800,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/womens/women9.png',
    name: 'Women Ruffled Brown Dress',
    price: 1300.0,
    offer: 2000,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/womens/women10.png',
    name: 'Women Fit and Flare Pink, Black Dress',
    price: 1450.0,
    offer: 1700,
    categories: 'womens',
  ),
];
List<AllDresses> boys = [
  AllDresses(
    image: 'assets/boys/boy1.png',
    name: 'Boys Party',
    price: 850.0,
    offer: 1200,
    categories: 'boys',
  ),
  AllDresses(
    image: 'assets/boys/boy2.png',
    name: 'Boys Casual Dress Pyjama',
    price: 350.0,
    offer: 500,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/boys/boy3.png',
    name: 'Boys Casual Shirt',
    price: 540.0,
    offer: 760,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/boys/boy4.png',
    name: 'Boys Party(Festive) Blazer Jeans ',
    price: 500.0,
    offer: 700,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/boys/boy5.png',
    name: 'Boys Casual Dress Dress ',
    price: 750.0,
    offer: 850,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/boys/boy6.png',
    name: 'Baby  Casual Top Capri',
    price: 1200.0,
    offer: 1300,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/boys/boy7.png',
    name: 'Baby Boys ',
    price: 800.0,
    offer: 1200,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/boys/boy8.png',
    name: 'Boys Casual T-shirt Track ',
    price: 760.0,
    offer: 900,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/boys/boy9.png',
    name: 'Boys Printed Pure Cotton',
    price: 230.0,
    offer: 450,
    categories: 'womens',
  ),
  AllDresses(
    image: 'assets/boys/boy10.png',
    name: 'Boys Casual Kurta ',
    price: 999.0,
    offer: 1350,
    categories: 'womens',
  ),
];
